CREATE TABLE TABLE (TABLE_ID INTEGER NOT NULL, MATERIEL VARCHAR, BONETAT BOOLEAN, PRIMARY KEY (TABLE_ID))
INSERT INTO TABLE VALUES (0, 'Bois', false)
INSERT INTO TABLE VALUES (1, 'Metal', true)
INSERT INTO TABLE VALUES (2, 'Nacre', true)