CREATE TABLE bureau (BUREAU_ID INTEGER NOT NULL, MATERIEL VARCHAR, BONETAT BOOLEAN, PRIMARY KEY (BUREAU_ID));
INSERT INTO bureau VALUES (0, 'BOIS', false);
INSERT INTO bureau VALUES (1, 'ACIER', true);
INSERT INTO bureau VALUES (2, 'PLASTIQUE', true);

CREATE TABLE chaise (CHAISE_ID INTEGER NOT NULL, MATERIEL VARCHAR, BONETAT BOOLEAN, PRIMARY KEY (CHAISE_ID));
INSERT INTO chaise VALUES (0, 'BOIS', false);
INSERT INTO chaise VALUES (1, 'ACIER', true);
INSERT INTO chaise VALUES (2, 'PLASTIQUE', true);