version: '2'
services:
    payara-full:
        build:
          context: .
          dockerfile: ./mypayara-full/Dockerfile
        ports:
            - "8080:8080"
            - "4848:4848"
        entrypoint:
            - asadmin
            - start-domain
            - -v
            - --postbootcommandfile=com.txt
        volumes:
            - ./data/payara:/opt/payara41/glassfish/domains/domain1/autodeploy
        depends_on:
            - db

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: glassfishdbpassword
            POSTGRES_USER: glassfish
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./data/pgdata:/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
